with open('app.py','r',encoding='utf-8') as f: c=f.read()
old = '</script>\n</body></html>"""'
audit_html = []
audit_html.append('  </div>')
audit_html.append('  <div id="admin-tab-audit" class="tab-panel">')
audit_html.append('    <div class="card">')
audit_html.append('      <div class="card-head">')
audit_html.append('        <h2>&#128203; Audit Log</h2>')
audit_html.append('        <div style="display:flex;gap:8px;align-items:center">')
audit_html.append('          <input class="search-box" placeholder="&#128269; Filter..." oninput="filterAudit(this.value)" style="width:200px">')
audit_html.append('          <button class="btn btn-ghost" onclick="loadAudit()">&#8635; Refresh</button>')
audit_html.append('        </div></div>')
audit_html.append('      <div style="overflow-x:auto"><table id="audit-table">')
audit_html.append('        <thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Target</th><th>Detail</th><th>IP</th></tr></thead>')
audit_html.append('        <tbody id="audit-tbody"><tr><td colspan="6" style="text-align:center;padding:20px;color:#999">Click Refresh to load</td></tr></tbody>')
audit_html.append('      </table></div></div></div>')
audit_html.append('<script>')
audit_html.append('function switchAdminTab(name,btn){')
audit_html.append('  document.querySelectorAll(".tab-panel").forEach(p=>p.classList.remove("active"))')
audit_html.append('  document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"))')
audit_html.append('  document.getElementById("admin-tab-"+name).classList.add("active")')
audit_html.append('  btn.classList.add("active")')
audit_html.append('  if(name==="audit")loadAudit()')
audit_html.append('}')
audit_html.append('function filterAudit(q){')
audit_html.append('  q=q.toLowerCase()')
audit_html.append('  document.querySelectorAll("#audit-table tbody tr").forEach(tr=>{')
audit_html.append('    tr.style.display=tr.textContent.toLowerCase().includes(q)?"":"none"')
audit_html.append('  })')
audit_html.append('}')
audit_html.append('function loadAudit(){')
audit_html.append('  fetch("/api/audit_log").then(r=>r.json()).then(rows=>{')
audit_html.append('    const ac=a=>{a=(a||"").toLowerCase();if(a.includes("login"))return"login";if(a.includes("delete")||a.includes("disable"))return"delete";if(a.includes("edit"))return"edit";return""}')
audit_html.append('    const tb=document.getElementById("audit-tbody")')
audit_html.append('    if(!rows.length){tb.innerHTML="<tr><td colspan=6 style=text-align:center;padding:20px;color:#999>No audit records yet</td></tr>";return}')
audit_html.append('    tb.innerHTML=rows.map(r=>`<tr><td style=white-space:nowrap;color:#666>${r.ts||""}</td><td style=font-weight:600>${r.actor_name||""}</td><td><span class="audit-action ${ac(r.action)}">${r.action||""}</span></td><td style=color:#666>${r.target_type||""} ${r.target_id||""}</td><td style=max-width:280px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap title="${r.detail||""}"><small>${r.detail||""}</small></td><td style=color:#999;font-size:10px>${r.ip||""}</td></tr>`).join("")')
audit_html.append('  }).catch(e=>document.getElementById("audit-tbody").innerHTML="<tr><td colspan=6 style=color:#ED1C24;padding:12px>Error: "+e.message+"</td></tr>")')
audit_html.append('}')
audit_html.append('</script>')
new_end = '\n'.join(audit_html) + '\n</body></html>"""'
if old in c:
    c = c.replace(old, new_end)
    print('Audit panel injected')
else:
    print('NOT MATCHED')
    print(repr(c[c.rfind('</script>')-20:c.rfind('</script>')+15]))
with open('app.py','w',encoding='utf-8') as f: f.write(c)